### ISSUE TITLE
raspimjpeg segfault

### ISSUE THREAD

**Issue by gregd72002** [silvanmelchior/RPi_Cam_Web_Interface#20]
Hi,

I was trying to get raspimjpeg to work to no avail. I compiled it using sources provided in here: https://github.com/silvanmelchior/userland

All other raspi* do work but raspimjpeg reports segfault. Is there a debug version I could try?

```
# ls
raspimjpeg  raspistill  raspivid    raspiyuv    tvservice   vcgencmd    vchiq_test
# /usr/bin/raspistill -o test.jpg  -hf -vf -w 1024 -h 768
# ls -la
total 748
drwxrwxr-x    2 root     root          1024 Jan  1 00:04 .
drwxrwxr-x    8 root     root          1024 Nov 26  2014 ..
-rwxr-xr-x    1 root     root         31872 Nov 26  2014 raspimjpeg
-rwxr-xr-x    1 root     root         82648 Nov 26  2014 raspistill
-rwxr-xr-x    1 root     root         52324 Nov 26  2014 raspivid
-rwxr-xr-x    1 root     root         44708 Nov 26  2014 raspiyuv
-rw-------    1 root     root        465259 Jan  1 00:04 test.jpg
-rwxr-xr-x    1 root     root         18248 Nov 26  2014 tvservice
-rwxr-xr-x    1 root     root          4796 Nov 26  2014 vcgencmd
-rwxr-xr-x    1 root     root         50940 Nov 26  2014 vchiq_test
# ./raspimjpeg --help
Error: Invalid arguments
# ./raspimjpeg -w 320 -h 240 -d 5 -of test1.jpg
Error: Invalid arguments
# ./raspimjpeg 
MJPEG streaming
Segmentation fault
# 
```

**Comment by geckus** [comment]
im trying to generate a thumbnail image file of the actual image about width:120px height:90px
is there a way to do it without recompiling the file?

**Comment by roberttidey** [comment]
The internal thumbnail width is controlled by the preview width setting but this will also affect the live video feed size as well.

If you want the smaller thumbnails for external use without changing the internal ones then one way to do that would be to use the end job macros to convert from either the existing thumbnails or the raw image. You could use something like imagemagick to do the conversion very simply.

**Comment by geckus** [comment]
Yes have tried that. Wanted to reduce image to 100kb but it took close to 30secs. While a snapshot is almost instantaneous

**Comment by geckus** [comment]
Just a suggestion, for viewing preview it's great to have small images, and still retain the high res version for other processing

**Comment by geckus** [comment]
Was trying to recompile by editing the c file but I haven't got the right file structure.

**Comment by roberttidey** [comment]
Image size reduction should be much quicker than that. To make it very fast you could also just reize the existing preview rather than resize the high res. That way you are resizing a relatively small image.

Not sure I understand the suggestion. The preview is already downsampled from the original. If you mean playback a video at reduced resolution in th eweb page, i.e. have two video resolutions then that is not really practical without a length conversion.

You should be able to compile easily by just doing a git clone of the raspimjpeg repository at https://github.com/roberttidey/userland This will create a userland folder. You need to install cmake with apt-get install. Then you just go into userland and type ./buildme  The first compile takes a while , maybe 10 minutes, but subsequent ones are much faster.

**Comment by geckus** [comment]
Great I will try it out. The website seems to be down. All the instructions on elinux seems like they have gone missing
