### ISSUE TITLE
Not aksing for PW

### ISSUE THREAD

**Issue by Zacki84** [silvanmelchior/RPi_Cam_Web_Interface#385]
Hi

I have a running system with webiopi and the RPi Cam Web Interface Livestream implemented with an iFrame. As I setup the system I didn´t setup the Password.
Webiopi - Port: 8000
RPi Cam Web Interface - Port: 9000
I wanted to do this now, and so I run the install.sh script
I setup everything (Username, PW,...) and everything is working excapt my WebiOpi :-(
So I dicided to restore my backup and create a manuall .htaccess file in /var/www (code is in html subfolder) and a .htpasswd file in /usr/local
But after reboot, the webbrowser donßt asked me for Username and PW
I found Issue #309, and there you write to change something in /etc/apache2/sites-available/raspicam.conf
But I don´t have this file. I have only 000-default.conf & default-ssl.conf
and the content between #309 and my is different. Do I have to create such an file?
What can I do to make this run?

Thanks

**Comment by roberttidey** [comment]
/etc/apache2/sites-available/raspicam.conf is created when the install.sh is run irrespective of whether username/password is created. If username/password is requested then install.sh will change the raspicam.conf file so that apache knows to use that. It will also create the htaccess files with the password as configured. You do not need to do any manual steps. install.sh also creates a link to raspicam.conf in the sites-enabled folder so that should be visible as well and normally should be the only file there.

If these are not there then either something went wrong during the install.sh or some other process subsequently deleted them.

I think I would start clean, install RPi Cam with username and password. CHeck that is working and verify you have the raspicam.conf file as described.

Then do the webiopi and check that raspicam.conf is still there.
