### ISSUE TITLE
Shutdown-button does not work  

### ISSUE THREAD

**Issue by hexxa6** [silvanmelchior/RPi_Cam_Web_Interface#409]
OS: (fresh) Raspbian Stretch 
HW: Raspberry Pi 3B, 64GB SD 

I can't shutdown the system with the webinterface-button. 
I think its a permission problem. 

Reboot does work.

**Comment by roberttidey** [comment]
I have just tested this on a fresh latest Stretch and it works for me.

During the install special permission is added to perform a sudo shutdown command to user www-data ( the user under which the web operates) so that this button works.

If you issue the command

sudo cat /etc/sudoers.d/RPI_Cam_Web_Interface

Then you should see the lines granting permission for user www-data to run the shutdown command

**Comment by hexxa6** [comment]
You are right. sry

I access my pi-cam over a wifi ad-hoc network with my iPhone.
The shutdown-button didn't worked and the the main buttons got haywire after a while. 

![img_20180324_220312_1504](https://user-images.githubusercontent.com/15018381/37934252-e4d841d4-314d-11e8-928e-4b30104e16b1.PNG)
After your post i just deleted the Safari (Browser) cache. And now everything just works fine 👍
