### ISSUE TITLE
Upgrading to 6.5.1 PHP7

### ISSUE THREAD

**Issue by mfraser** [silvanmelchior/RPi_Cam_Web_Interface#502]
Just upgraded 2 installs of RPi Cam to 6.5.1 and on the first one I didn't notice that the PHP line had changed from 5/7 to 7.0 7.3 and just left it at 7. The installer then complained that
E: Unable to locate package php7
E: Unable to locate package php7-cli
E: Unable to locate package libapache2-mod-php7
Does there need to be a check added to validate the answer?

**Comment by roberttidey** [comment]
Yes, the explicit php version now needs to be put in. This is due to different OS requirements (stertch 7.0, buster 7.3)

I'll look at putting something in to avoid the mistake when just 7 is left from a previous version. Maybe just convert 7 to 7.0 as this is likely to just occur when doing an upgrade rather than loading a new OS.
